name: vault_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  camera: ^0.11.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  image_picker: ^1.1.2
  mime: ^2.0.0
  open_file: ^3.5.10
  provider: ^6.1.5
  rive : ^0.13.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/uploads/
    - assets/uploads/files/
    - assets/samples/animations/
    - assets/samples/ui/rive_app/
    - assets/samples/ui/rive_app/rive/
    - assets/samples/ui/rive_app/images/
    - assets/samples/ui/rive_app/images/backgrounds/
    - assets/samples/ui/rive_app/images/topics/
    - assets/samples/ui/rive_app/images/avatars/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 900

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
